services:
  database:
    build:
      context: ./db/
      dockerfile: Dockerfile
      target: 'database'
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: todos
      TZ: Asia/Tokyo
    restart: always

  # app:
  #   container_name: app
  #   build:
  #     context: ./app
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 5173:5173
  #   volumes:
  #     - ./app:/app

volumes:
  pgdata:
